"""initial migrations 2

Revision ID: 68eabb1ea3d7
Revises: e9a916ca9cbb
Create Date: 2024-01-23 16:09:10.390693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68eabb1ea3d7'
down_revision: Union[str, None] = 'e9a916ca9cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
