"""initial migrations

Revision ID: e9a916ca9cbb
Revises: 6d849a81726f
Create Date: 2024-01-23 16:08:36.203915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a916ca9cbb'
down_revision: Union[str, None] = '6d849a81726f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bono',
    sa.Column('monto_usd', sa.DECIMAL(precision=100, scale=2), nullable=True),
    sa.Column('monto_bs', sa.DECIMAL(precision=100, scale=2), nullable=True),
    sa.Column('aplica_arreglo', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bono_id'), 'bono', ['id'], unique=False)
    op.create_table('cargo',
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_index(op.f('ix_cargo_id'), 'cargo', ['id'], unique=False)
    op.create_table('departamento',
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_index(op.f('ix_departamento_id'), 'departamento', ['id'], unique=False)
    op.create_table('empleado',
    sa.Column('naturaleza', sa.Enum('VENEZOLANO', 'EXTRANJERO', 'JURIDICO', name='natureenum'), nullable=True),
    sa.Column('identificacion', sa.String(length=14), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('sexo', sa.Enum('MASCULINO', 'FEMENINO', name='sexenum'), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_contratacion', sa.Date(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('foto', sa.String(), nullable=True),
    sa.Column('salario', sa.DECIMAL(precision=100, scale=2), nullable=True),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empleado_id'), 'empleado', ['id'], unique=False)
    op.create_index(op.f('ix_empleado_identificacion'), 'empleado', ['identificacion'], unique=True)
    op.create_index(op.f('ix_empleado_naturaleza'), 'empleado', ['naturaleza'], unique=False)
    op.create_table('empleado_bono',
    sa.Column('bono_id', sa.Integer(), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bono_id'], ['bono.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empleado_bono_id'), 'empleado_bono', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_empleado_bono_id'), table_name='empleado_bono')
    op.drop_table('empleado_bono')
    op.drop_index(op.f('ix_empleado_naturaleza'), table_name='empleado')
    op.drop_index(op.f('ix_empleado_identificacion'), table_name='empleado')
    op.drop_index(op.f('ix_empleado_id'), table_name='empleado')
    op.drop_table('empleado')
    op.drop_index(op.f('ix_departamento_id'), table_name='departamento')
    op.drop_table('departamento')
    op.drop_index(op.f('ix_cargo_id'), table_name='cargo')
    op.drop_table('cargo')
    op.drop_index(op.f('ix_bono_id'), table_name='bono')
    op.drop_table('bono')
    # ### end Alembic commands ###
